// AvroBangla Engine - wraps riti for macOS IME use
//
// This crate re-exports riti's FFI and adds macOS-specific helpers.
// riti's #[no_mangle] extern "C" functions are automatically included
// in the static library output.

// Force riti to be linked (ensures FFI symbols are included)
extern crate riti;

// Re-export riti's keycodes module for reference
pub use riti::keycodes;

/// Convert a macOS character (from NSEvent.characters) to a riti keycode.
/// Returns 0 if the character is not mapped.
#[no_mangle]
pub extern "C" fn avro_keycode_for_char(ch: u32) -> u16 {
    match char::from_u32(ch) {
        Some('`') => riti::keycodes::VC_GRAVE,
        Some('~') => riti::keycodes::VC_TILDE,
        Some('1') => riti::keycodes::VC_1,
        Some('2') => riti::keycodes::VC_2,
        Some('3') => riti::keycodes::VC_3,
        Some('4') => riti::keycodes::VC_4,
        Some('5') => riti::keycodes::VC_5,
        Some('6') => riti::keycodes::VC_6,
        Some('7') => riti::keycodes::VC_7,
        Some('8') => riti::keycodes::VC_8,
        Some('9') => riti::keycodes::VC_9,
        Some('0') => riti::keycodes::VC_0,
        Some('!') => riti::keycodes::VC_EXCLAIM,
        Some('@') => riti::keycodes::VC_AT,
        Some('#') => riti::keycodes::VC_HASH,
        Some('$') => riti::keycodes::VC_DOLLAR,
        Some('%') => riti::keycodes::VC_PERCENT,
        Some('^') => riti::keycodes::VC_CIRCUM,
        Some('&') => riti::keycodes::VC_AMPERSAND,
        Some('*') => riti::keycodes::VC_ASTERISK,
        Some('(') => riti::keycodes::VC_PAREN_LEFT,
        Some(')') => riti::keycodes::VC_PAREN_RIGHT,
        Some('-') => riti::keycodes::VC_MINUS,
        Some('_') => riti::keycodes::VC_UNDERSCORE,
        Some('=') => riti::keycodes::VC_EQUALS,
        Some('+') => riti::keycodes::VC_PLUS,
        Some('a') => riti::keycodes::VC_A,
        Some('b') => riti::keycodes::VC_B,
        Some('c') => riti::keycodes::VC_C,
        Some('d') => riti::keycodes::VC_D,
        Some('e') => riti::keycodes::VC_E,
        Some('f') => riti::keycodes::VC_F,
        Some('g') => riti::keycodes::VC_G,
        Some('h') => riti::keycodes::VC_H,
        Some('i') => riti::keycodes::VC_I,
        Some('j') => riti::keycodes::VC_J,
        Some('k') => riti::keycodes::VC_K,
        Some('l') => riti::keycodes::VC_L,
        Some('m') => riti::keycodes::VC_M,
        Some('n') => riti::keycodes::VC_N,
        Some('o') => riti::keycodes::VC_O,
        Some('p') => riti::keycodes::VC_P,
        Some('q') => riti::keycodes::VC_Q,
        Some('r') => riti::keycodes::VC_R,
        Some('s') => riti::keycodes::VC_S,
        Some('t') => riti::keycodes::VC_T,
        Some('u') => riti::keycodes::VC_U,
        Some('v') => riti::keycodes::VC_V,
        Some('w') => riti::keycodes::VC_W,
        Some('x') => riti::keycodes::VC_X,
        Some('y') => riti::keycodes::VC_Y,
        Some('z') => riti::keycodes::VC_Z,
        Some('A') => riti::keycodes::VC_A_SHIFT,
        Some('B') => riti::keycodes::VC_B_SHIFT,
        Some('C') => riti::keycodes::VC_C_SHIFT,
        Some('D') => riti::keycodes::VC_D_SHIFT,
        Some('E') => riti::keycodes::VC_E_SHIFT,
        Some('F') => riti::keycodes::VC_F_SHIFT,
        Some('G') => riti::keycodes::VC_G_SHIFT,
        Some('H') => riti::keycodes::VC_H_SHIFT,
        Some('I') => riti::keycodes::VC_I_SHIFT,
        Some('J') => riti::keycodes::VC_J_SHIFT,
        Some('K') => riti::keycodes::VC_K_SHIFT,
        Some('L') => riti::keycodes::VC_L_SHIFT,
        Some('M') => riti::keycodes::VC_M_SHIFT,
        Some('N') => riti::keycodes::VC_N_SHIFT,
        Some('O') => riti::keycodes::VC_O_SHIFT,
        Some('P') => riti::keycodes::VC_P_SHIFT,
        Some('Q') => riti::keycodes::VC_Q_SHIFT,
        Some('R') => riti::keycodes::VC_R_SHIFT,
        Some('S') => riti::keycodes::VC_S_SHIFT,
        Some('T') => riti::keycodes::VC_T_SHIFT,
        Some('U') => riti::keycodes::VC_U_SHIFT,
        Some('V') => riti::keycodes::VC_V_SHIFT,
        Some('W') => riti::keycodes::VC_W_SHIFT,
        Some('X') => riti::keycodes::VC_X_SHIFT,
        Some('Y') => riti::keycodes::VC_Y_SHIFT,
        Some('Z') => riti::keycodes::VC_Z_SHIFT,
        Some('[') => riti::keycodes::VC_BRACKET_LEFT,
        Some(']') => riti::keycodes::VC_BRACKET_RIGHT,
        Some('\\') => riti::keycodes::VC_BACK_SLASH,
        Some('{') => riti::keycodes::VC_BRACE_LEFT,
        Some('}') => riti::keycodes::VC_BRACE_RIGHT,
        Some('|') => riti::keycodes::VC_BAR,
        Some(';') => riti::keycodes::VC_SEMICOLON,
        Some('\'') => riti::keycodes::VC_APOSTROPHE,
        Some(',') => riti::keycodes::VC_COMMA,
        Some('.') => riti::keycodes::VC_PERIOD,
        Some('/') => riti::keycodes::VC_SLASH,
        Some(':') => riti::keycodes::VC_COLON,
        Some('"') => riti::keycodes::VC_QUOTE,
        Some('<') => riti::keycodes::VC_LESS,
        Some('>') => riti::keycodes::VC_GREATER,
        Some('?') => riti::keycodes::VC_QUESTION,
        _ => 0,
    }
}
